# Generated by Django 5.0.6 on 2024-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="idOfUser_fk",
            field=models.IntegerField(default=1),
        ),
    ]
